
Simple string interpolation using OCaml's ppx extension points API.

* How to use

Write [%str "some string"] anywhere a string expression is expected. Use $(name)
to insert the value of variable "name" whose types needs to be string. Use $$ to
insert an actual dollar character.

#+begin_src tuareg
let name = "mario" in
print_string [%str "It's a meee, $(name)\n"]
#+end_src

See directory src_test for examples on what to do and not to do.

* How to build

- install OCaml 4.02 (or newer)
- install opam 1.1.1 (or newer)
- install dependencies
  opam install sedlex ppx_tools ppx_deriving
- make all
  
Test by running 'make test'

* Todo

  - support arbitrary OCaml expressions inside $(...). Needs to run the OCaml
    lexer on the string, skip over balanced parenthesis and pass this to OCaml
    Parse.expression.
  - check if to_str_code can be simplified using Ast_convenience.list
  - Use Utf8 instead of Latin1, check for valid identifier

* Contact

Mail to jan@sheijk.net for questions and comments.

